version: '3.8'

services:
  # 1. Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_demo
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # 2. Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_demo
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # 3. Node Exporter (Giám sát phần cứng máy chủ)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"

