global:
  scrape_interval: 5s

scrape_configs:
  # Job 1: Ứng dụng Spring Boot của bạn
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # host.docker.internal tự động trỏ về máy tính thật của bạn
      - targets: ['host.docker.internal:8080']

  # Job 2: Giám sát phần cứng (CPU/RAM máy chủ)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

